import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { DndContext, useDraggable, useDroppable } from "@dnd-kit/core";
import { api } from "~/utils/api";
import { clsx } from "clsx";
import { create } from "zustand";
import { XCircleIcon } from "@heroicons/react/24/outline";
import Fuse from "fuse.js";

import { motion } from "framer-motion";
import { SearchField } from "~/components/Search";
import { useState } from "react";
interface IssueState {
  days: {
    monday: string[];
    tuesday: string[];
    wednesday: string[];
    thursday: string[];
    friday: string[];
  };
  addIssue: (issue: string, day: keyof IssueState["days"]) => void;
  removeIssue: (issue: string, day: keyof IssueState["days"]) => void;
}
const useIssuesStore = create<IssueState>((set) => ({
  days: {
    monday: ["aa"],
    tuesday: [],
    wednesday: [],
    thursday: [],
    friday: [],
  },
  addIssue: (issue, day) =>
    set((state) => ({
      days: {
        ...state.days,
        [day]: state.days[day].includes(issue)
          ? state.days[day]
          : [...state.days[day], issue],
      },
    })),
  removeIssue: (issue, day) =>
    set((state) => ({
      days: {
        ...state.days,
        [day]: state.days[day].filter((i) => i !== issue),
      },
    })),
}));

const Home: NextPage = () => {
  const query = api.jiraRouter.issues.useQuery();
  const addIssue = useIssuesStore((state) => state.addIssue);
  if (query.data) {
    console.log(query.data);
  }
  return (
    <>
      <Head>
        <title>Tracky</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto min-h-screen space-y-2">
        <h1 className="pt-4 text-xl text-slate-700">Tracky</h1>
        <div className="container flex space-x-2">
          <DndContext
            onDragEnd={(e) => {
              if (e.active.id && e.over?.id) {
                addIssue(
                  e.active.id as string,
                  e.over.id as keyof IssueState["days"]
                );
              }
            }}
          >
            <div className="w-2/3">
              <Issues />
            </div>

            <div className="flex w-1/3 flex-col space-y-6">
              <Day label="monday" />
              <Day label="tuesday" />
              <Day label="wednesday" />
              <Day label="thursday" />
              <Day label="friday" />
            </div>
          </DndContext>
        </div>
      </main>
    </>
  );
};
type DayProps = {
  label: keyof IssueState["days"];
};
const Day = (props: DayProps) => {
  const { isOver, setNodeRef } = useDroppable({
    id: props.label,
  });
  const issues = useIssuesStore((state) => state.days[props.label]);
  const removeIssues = useIssuesStore((state) => state.removeIssue);
  const capitalize = (s: string) => {
    return s.charAt(0).toUpperCase() + s.slice(1);
  };

  return (
    <div
      className={clsx(
        "space-y-1 rounded border-2 border-slate-300 p-2",
        isOver ? "bg-green-200" : "bg-slate-50"
      )}
      ref={setNodeRef}
    >
      <h1 className="text-xl font-light text-green-900">
        {capitalize(props.label)}
      </h1>
      <div className="grid grid-cols-2 gap-2">
        {issues.map((issue) => (
          <div
            key={issue}
            className="flex flex-row items-center justify-between rounded-lg bg-emerald-200 px-3 py-2"
          >
            <p className="text-emerald-900">{issue}</p>
            <XCircleIcon
              className="h-5 w-5 cursor-pointer text-emerald-800"
              onClick={() => removeIssues(issue, props.label)}
            />
          </div>
        ))}
      </div>
    </div>
  );
};

type IssueProps = {
  title: string;
  id: string;
  epic?: string;
};
const Issue = (props: IssueProps) => {
  const { attributes, listeners, setNodeRef, transform } = useDraggable({
    id: props.id,
  });

  const style = transform
    ? {
        transform: `translate3d(${transform.x}px, ${transform.y}px, 0)`,
      }
    : undefined;

  return (
    <div {...listeners} {...attributes} style={style} ref={setNodeRef}>
      <motion.div
        className=" flex h-full flex-col space-y-1 rounded bg-emerald-200 p-4"
        whileHover={{
          scale: 1.05,
        }}
      >
        <div className="flex flex-row items-center justify-between">
          <p className="font-semibold text-emerald-800">{props.title}</p>
          <p className="text-sm font-light text-emerald-900">{props.id}</p>
        </div>
        <p className="text-sm text-emerald-800">{props.epic}</p>
      </motion.div>
    </div>
  );
};

const Issues = () => {
  const query = api.jiraRouter.issues.useQuery(undefined, {
    placeholderData: [],
  });
  const [search, setSearch] = useState("");

  if (query.isLoading) {
    return <div>loading</div>;
  }
  if (query.isError) {
    return <div>error</div>;
  }

  const fuse = new Fuse(query.data, {
    keys: ["title", "epic"],
    ignoreLocation: true,
  });

  const result = fuse.search(search).map((r) => r.item);
  console.log(result);

  const data = search === "" ? query.data : result;

  return (
    <div className="space-y-4 rounded border-2 border-slate-300 p-6">
      <div className="flex flex-row items-center space-x-4 ">
        <h1 className="text-xl font-light text-slate-700"> Issues</h1>
        <SearchField value={search} onChange={(val) => setSearch(val)} />
      </div>
      <div className="grid grid-cols-3 gap-4">
        {data.map((issue) => (
          <Issue
            key={issue.id}
            title={issue.title}
            id={issue.key}
            epic={issue.epic}
          />
        ))}
      </div>
    </div>
  );
};

export default Home;
